---
controller_repo_url: "https://github.com/scbitworx/ansible-controller.git"

base_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpJt9FKTaxGMfOvNKoOG1hVXHSqU8MeBXhV8mYOsHrr ceres"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpVMxvFG7Xkb3UtB4MdOxcGRiVMYNGC0hIk9dONSZbQ mars"
